# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
inhibit_all_warnings!
use_frameworks!

def testing_pods
    pod 'Quick'
    pod 'Nimble'
end
target 'MarvelDemoApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for MarvelDemoApp

  target 'MarvelDemoAppTests' do
    inherit! :search_paths
   testing_pods
  end

  target 'MarvelDemoAppUITests' do
    inherit! :search_paths
    testing_pods
    
  end

end
